 # 1.  Problem: A fair six-sided die is rolled 100 times. What is the probability of rolling exactly five 3's?
 Data: Number of rolls (n) = 100

In [11]:
from scipy.stats import binom

n=100
p=1/6
k=5
# Binomial Distribution:-
prob = binom.pmf(k,n,p)
print(f"The Prob of rolling the exactly 5 3's is: {prob:.6f}")

The Prob of rolling the exactly 5 3's is: 0.000291


# 2. Problem: In a deck of 52 playing cards, five cards are randomly drawn without replacement. What is the probability of getting two hearts?

Data: Number of hearts in the deck (N) = 13, Number of cards drawn (n) = 5

In [34]:
from math import comb
N=52
n=5
total_Hearts = 13
two_hearts = 2 

num = comb(total_Hearts,two_hearts)*comb(N-total_Hearts,n-two_hearts)
deno = comb(N,n)

prob_of_getting_two_hearts = num/deno

print(f"The prob of getting the two hearts is: {prob_of_getting_two_hearts:.5f}")

The prob of getting the two hearts is: 0.27428


# 3.  Problem: A multiple-choice test consists of 10 questions, each with four possible answers. If a student randomly guesses on each question, what is the probability of getting at least 8 questions correct?
 Data: Number of questions (n) = 10, Number of possible answers per question (k) = 4

In [41]:
n=10
p=1/4

# Usiing the binomial distrubution:- 

prob = binom.pmf(8,n,p) + binom.pmf(9,n,p) + binom.pmf(10,n,p)
print(f"The prob of getting atleast 8 questions correct is: {prob:.6f}")

The prob of getting atleast 8 questions correct is: 0.000416


# 4. . Problem: A bag contains 30 red balls, 20 blue balls, and 10 green balls. Three balls are drawn without replacement. What is the probability that all three balls are blue?
 Data: Number of blue balls in the bag (N) = 20, Number of balls drawn (n) = 3

In [49]:
N=60
n=3
K=20
k=3

# Using the hypergeometric rule:-
num = comb(K,k)*comb(N-K,n-k)
deno = comb(N,n)

Probability = num / deno
print(f"The Probability of getting all 3 balls blue is: {Probability:.5f}")

The Probability of getting all 3 balls blue is: 0.03331


# 5. Problem: In a football match, a player scores a goal with a 0.3 probability per shot. If the player takes 10 shots, what is the probability of scoring exactly three goals?

Data: Number of shots (n) = 10, Probability of scoring per shot (p) = 0.3

In [54]:
n=10 
p=0.3
k=3

prob = binom.pmf(k,n,p)
print(f"The prob of scoring exactly 3 goals is: {prob:.5f}")

The prob of scoring exactly 3 goals is: 0.26683


# 6. Problem: The heights of students in a class are normally distributed with a mean of 165 cm and a standard deviation of 10 cm. What is the probability that a randomly selected student is taller than 180 cm?
 Data: Mean height (μ) = 165 cm, Standard deviation (σ) = 10 cm, Height threshold (x)
 = 180 cm

In [5]:
from scipy.stats import norm 
mean = 165 
s_d = 10
x=180

# Using the z-normal distribution:-
prob = 1-norm.cdf(x,loc=mean,scale=s_d)
print(f"The prob that randomly selected student taller than 180cm is: {prob:.5f}")

The prob that randomly selected student taller than 180cm is: 0.06681


# 7. Problem: The waiting times at a coffee shop are exponentially distributed with a mean of 5 minutes. What is the probability that a customer waits less than 3 minutes?
 Data: Mean waiting time (μ) = 5 minutes, Waiting time threshold (x) = 3 minutes 

In [18]:
from scipy.stats import expon
mean = 5
x=3

# Uing the exponential distribution function:-
prob = expon.cdf(x,scale=mean)
print(f"The prob of waiting time for a customer for less than 3 min is: {prob:.4f}")

The prob of waiting time for a customer for less than 3 min is: 0.4512


# 8. Problem: The lifetimes of a certain brand of light bulbs are normally distributed with amean of 1000 hours and a standard deviation of 100 hours. What is the probability thata randomly selected light bulb lasts between 900 and 1100 hours?
Data: Mean lifetime (μ) = 1000 hours, Standard deviation (σ) = 100 hours, Lifetime
 range (lower limit x1, upper limit x2)

In [26]:
mean = 1000 
s_d = 100
x1=900
x2=1100

lower_limit = 1-norm.cdf(x1,loc=mean,scale=s_d)
upper_limit = 1-norm.cdf(x2,loc=mean, scale=s_d)

prob = lower_limit - upper_limit

print(f"The prob of the light bulbs in lower limit is: {lower_limit:.4f}")
print(f"The prob of the light bulbs in the upper limit is: {upper_limit:.4f}")
print(f"The prob of randomly selected light bulbs lasting between 900 and 1100 is: {prob:.4f}")

The prob of the light bulbs in lower limit is: 0.8413
The prob of the light bulbs in the upper limit is: 0.1587
The prob of randomly selected light bulbs lasting between 900 and 1100 is: 0.6827


# 9. Problem: The weights of apples in a basket follow a uniform distribution between 100 grams and 200 grams. What is the probability that a randomly selected apple weighs between 150 and 170 grams?
 Data: Weight range (lower limit x1, upper limit x2)

In [39]:
from scipy.stats import uniform
a=100
b=200
x1=150
x2=170

# using the uniform distribution:-
u_d = uniform(loc=a,scale=b-a)
# Using the random distribution to find the probability:-(cdf)
prob = u_d.cdf(x2) - u_d.cdf(x1)

print(f"The Prob of the randomly selected apples weighs between the 150 and 170 grams is: {prob:.4f}")

The Prob of the randomly selected apples weighs between the 150 and 170 grams is: 0.2000


# 10.  Problem: The time taken to complete a task is exponentially distributed with a mean of 20 minutes. What is the probability that the task is completed in less than 15 minutes?
 Data: Mean time (μ) = 20 minutes, Time threshold (x) = 15 minutes

In [46]:
mean = 20
x=15

# Using the exponential prob deistribuition funciton:-
prob = expon.cdf(x,scale=mean)
print(f"The prob of the task completed less than 15 min is: {prob:.4f}")

The prob of the task completed less than 15 min is: 0.5276


# 11.  Problem: A company sells smartphones, and the number of defects per batch follows a Poisson distribution with a mean of 2 defects. What is the probability of having exactly 3 defects in a randomly selected batch?
 Data: Mean number of defects (λ) = 2, Number of defects (x) = 3

In [58]:
from scipy.stats import poisson
lam_ = 2
x=3

# Using the posion distribution:-
prob = poisson.pmf(x,lam_)
print(f"The prob of having exactly 3 defects in a randomly selected batch is: {prob:.4f}")

The prob of having exactly 3 defects in a randomly selected batch is: 0.1804


# 12.  Problem: In a game, a player has a 0.3 probability of winning each round. If the player plays 10 rounds, what is the probability of winning exactly 3 rounds?
 Data: Probability of winning (p) = 0.3, Number of rounds (n) = 10, Number of wins (x)
 = 3

In [67]:
from scipy.stats import binom
p=0.3
N=10
x=3

# Independent distribution (using the discrete binomial distribution):-
prob = binom.pmf(x,N,p)
print(f"The prob of the winning exactly 3 rounds is : {prob:.4f}")

The prob of the winning exactly 3 rounds is : 0.2668


# 13.  Problem: A six-sided fair die is rolled three times. What is the probability of obtaining at least one 6?
 Data: Number of rolls (n) = 3

In [72]:
p=1/6
n=3
x=6

# Finding the prob of getting zero six:-(Discrete distribution)
p_zero_six = binom.pmf(0,n,p)

# Finding the prob of the atleast one 6 after rolling the die:-
prob_of_one_six = 1-p_zero_six
print(f"The prob of getting the zero sixes is: {p_zero_six:.4f}")
print(f"The prob of obtaining atleast one six is: {prob_of_one_six:.4f}")

The prob of getting the zero sixes is: 0.5787
The prob of obtaining atleast one six is: 0.4213


# 14. . Problem: The weights of apples in a basket follow a normal distribution with a mean of 150 grams and a standard deviation of 10 grams. What is the probability that a randomly selected apple weighs between 140 and 160 grams?
 Data: Mean weight (μ) = 150 grams, Standard deviation (σ) = 10 grams, Weight range
 (lower limit x1, upper limit x2)

In [75]:
from scipy.stats import norm

mean = 150
s_d = 10
x1=140
x2=160

lower_limit= 1-norm.cdf(x1,loc=mean,scale=s_d)
upper_limit= 1-norm.cdf(x2,loc=mean,scale=s_d)
# finding the prob of randomly selected apples:-
prob = lower_limit - upper_limit
print(f"The prob of the getting randomly selected apples weighing between the 140 and 160 grams is: {prob:.4f}")

The prob of the getting randomly selected apples weighing between the 140 and 160 grams is: 0.6827


# 15. . Problem: The lifetimes of a certain brand of light bulbs are exponentially distributed with a mean of 1000 hours. What is the probability that a randomly selected light bulb lasts more than 900 hours?
 Data: Mean lifetime (μ) = 1000 hours, Lifetime threshold (x) = 900 hours

In [82]:
mean = 1000
x=900

# Using the exponential distribution :-
prob = expon.cdf(x,scale=mean)
print(f"The prob of the randomly selected light bulbs lasting more than 900 hours is: {prob:.4f}")

The prob of the randomly selected light bulbs lasting more than 900 hours is: 0.5934


# 16.  Problem: A study is conducted to estimate the mean height of a population. A random sample of 100 individuals is selected, and their heights are measured. Calculate a 95% confidence interval for the population mean height, given that the sample mean height is 170 cm and the sample standard deviation is 8 cm.
 Data: Sample size (n) = 100, Sample mean (x) = 170 cm, Sample standard deviation
 (s) = 8 cm, Confidence level = 95%

In [99]:
import math
import scipy.stats as stats
n=100
c_i = 0.95
s_mean = 170
s_d = 8

# finding the std error:-
s_e = s_d / math.sqrt(n)

# Finding the Z_Score:-
Z_score=stats.norm.ppf(1-(1-c_i)/2)

# Finding the Marginal error:-
M_E = s_e * Z_score

# Calculating the lower and upper limit:-
lower_limit = s_mean - M_E
upper_limit = s_mean + M_E
print(f"The 95% Confidance interval for the poputlation mean height is: {lower_limit:.4f}, {upper_limit:.4f}")

The 95% Confidance interval for the poputlation mean height is: 168.4320, 171.5680


# 17. Problem: A survey is conducted to estimate the proportion of people in a city who support a particular policy. A random sample of 500 individuals is surveyed, and 320 of them express support for the policy. Calculate a 90% confidence interval for the population proportion, given the sample proportion.
 Data: Sample size (n) = 500, Number of successes (x) = 320, Confidence level = 90%

In [104]:
n=500
x=320
c_i=0.90

# calulatinng the std_error:-
s_e=s_mean/math.sqrt(n)

# Calculating the Z_Score:-
Z_score = stats.norm.ppf(1-(1-c_i)/2)

# Calculating the marginal error:-
M_E = Z_score * s_e

# Calculating the lower and upper limit:-
lower_limit=x-M_E
upper_limit=x+M_E


print(f"The 90% Confidance Interval for the population is: {lower_limit:.4f}, {upper_limit:.4f}")

The 90% Confidance Interval for the population is: 307.4948, 332.5052


# 18. Problem: A manufacturing company claims that the average weight of its product is 500 grams. To test this claim, a random sample of 25 products is selected, and their weights are measured. The sample mean weight is found to be 510 grams with a sample standard deviation of 20 grams. Perform a hypothesis test to determine if there is evidence to support the company's claim.
 Data: Sample size (n) = 25, Sample mean (x) = 510 grams, Sample standard
 deviation (s) = 20 grams, Population mean (μ) = 500 grams

In [127]:
n=25
s_mean = 510
s_d=20
mu=500
alpha = 0.05
d_f=n-1

# Calculating the t-stats:-
t_stats = (s_mean - mu) / (s_d/math.sqrt(n))

# using the two tail test:-
p_value = 2* (1-stats.t.cdf(abs(t_stats),d_f))

# Calcluating the critical value:-
critical_value = stats.t.ppf(1-alpha/2,d_f)


print(f"The t_stats value is: {t_stats:.4f}")
print(f"The prob value of two tail test is: {p_value:.4f}")
print(f"The critical value is: {critical_value:.4f}")

if 

The t_stats value is: 2.5000
The prob value of two tail test is: 0.0197
The critical value is: 2.0639
